# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Cristian Cezar Moisés
# Commercial licensing: sac@securityops.co
services:
  zupt:
    build:
      context: .
      network: host
    ports:
      - "8181:8080"
    restart: no
